package net.mcreator.crustychunks.init;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber.Bus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

@EventBusSubscriber(
   bus = Bus.MOD
)
public class CrustyChunksModTabs {
   public static final DeferredRegister<CreativeModeTab> REGISTRY;
   public static final RegistryObject<CreativeModeTab> CRUSTY_ORES;
   public static final RegistryObject<CreativeModeTab> CRUSTY_PRODUCTION;
   public static final RegistryObject<CreativeModeTab> WARIUM_LOGISTICS;
   public static final RegistryObject<CreativeModeTab> CRUSTY_COMPONENTS;
   public static final RegistryObject<CreativeModeTab> CRUSTY_BUILDING;
   public static final RegistryObject<CreativeModeTab> WARIUM_AMMUNITION;
   public static final RegistryObject<CreativeModeTab> CRUSTY_ARSENAL;
   public static final RegistryObject<CreativeModeTab> CRUSTY_EXPLOSIVES;
   public static final RegistryObject<CreativeModeTab> WARIUM_ARMOR;
   public static final RegistryObject<CreativeModeTab> WARIUM_ALUMINUM;

   @SubscribeEvent
   public static void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {
      if (tabData.getTabKey() == CreativeModeTabs.f_256731_) {
         tabData.m_246326_((ItemLike)CrustyChunksModItems.DECIMATOR_SPAWN_EGG.get());
         tabData.m_246326_((ItemLike)CrustyChunksModItems.STRIKER_SPAWN_EGG.get());
         tabData.m_246326_((ItemLike)CrustyChunksModItems.FLAMER_SPAWN_EGG.get());
         tabData.m_246326_((ItemLike)CrustyChunksModItems.HUNTER_SPAWN_EGG.get());
         tabData.m_246326_((ItemLike)CrustyChunksModItems.RIFLER_SPAWN_EGG.get());
         tabData.m_246326_((ItemLike)CrustyChunksModItems.MORTARER_SPAWN_EGG.get());
         tabData.m_246326_((ItemLike)CrustyChunksModItems.COMMANDER_SPAWN_EGG.get());
         tabData.m_246326_((ItemLike)CrustyChunksModItems.CIWS_SPAWN_EGG.get());
         tabData.m_246326_((ItemLike)CrustyChunksModItems.ASSASSIN_SPAWN_EGG.get());
         tabData.m_246326_((ItemLike)CrustyChunksModItems.ERADICATOR_SPAWN_EGG.get());
         tabData.m_246326_((ItemLike)CrustyChunksModItems.SCOUT_SPAWN_EGG.get());
         tabData.m_246326_((ItemLike)CrustyChunksModItems.WORKER_SPAWN_EGG.get());
         tabData.m_246326_((ItemLike)CrustyChunksModItems.REAPER_SPAWN_EGG.get());
         tabData.m_246326_((ItemLike)CrustyChunksModItems.BREACHER_SPAWN_EGG.get());
      }

   }

   static {
      REGISTRY = DeferredRegister.create(Registries.f_279569_, "crusty_chunks");
      CRUSTY_ORES = REGISTRY.register("crusty_ores", () -> {
         return CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.crusty_chunks.crusty_ores")).m_257737_(() -> {
            return new ItemStack((ItemLike)CrustyChunksModItems.ZINC_INGOT.get());
         }).m_257501_((parameters, tabData) -> {
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ZINC_INGOT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BRASS_INGOT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.STEEL_INGOT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LEAD_INGOT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.NICKEL_INGOT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ALUMINUM_INGOT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.URANIUM_DEPLETED_INGOT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.URANIUM_NEURAL_INGOT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.URANIUM_ENRICHED_INGOT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BERYLLIUM_INGOT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LITHIUM_INGOT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ENRICHED_LITHIUM_INGOT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.PLUTONIUM_INGOT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.RAW_ZINC.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.RAW_LEAD.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.RAW_NICKEL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.RAW_URANIUM.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.RAW_BERYLLIUM.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.RAW_LITHIUM.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SULFUR.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.TRINITITE_SHARD.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.IRON_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.GOLD_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.COPPER_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ZINC_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BRASS_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LEAD_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.NICKEL_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BAUXITE_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ALUMINUM_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ALUMINUM_TINY_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.URANIUM_NEUTRAL_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.URANIUM_NEUTRALTINY_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.URANIUM_ENRICHED_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.URANIUM_ENRICHED_TINY_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.URANIUM_DEPLETED_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.URANIUM_DEPLETED_TINY_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BERYLLIUM_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LITHIUM_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LITHIUM_DEUTERIDE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.TINY_LITHIUM_DEUTERIDE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LEAD_NUGGET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LITHIUM_NUGGET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ENRICHED_LITHIUM_NUGGET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.PLUTONIUM_NUGGET.get());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ZINC_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BRASS_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.STEEL_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LEAD_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.NICKEL_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BERYLLIUM_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LITHIUM_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.SULFUR_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RAW_ZINC_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RAW_LEAD_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RAW_NICKEL_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RAW_URANIUM_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RAW_BERYLLIUM_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RAW_LITHIUM_BLOCK.get()).m_5456_());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SHALE_OIL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.CRUDE_OIL_BUCKET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.OIL_BUCKET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.DIESEL_BUCKET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.KEROSENE_BUCKET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.PETROLIUM_BUCKET.get());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.TAR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ZINC_ORE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LEAD_ORE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.DEEPSLATE_LEAD_ORE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.NICKEL_ORE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.SULFUR_ORE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.URANIUM_ORE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BERYLLIUM_ORE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LITHIUM_ORE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BAUXITE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.TRINITITE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RADIOACTIVE_ASH_FULL_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RADIOACTIVE_ASH.get()).m_5456_());
         }).m_257652_();
      });
      CRUSTY_PRODUCTION = REGISTRY.register("crusty_production", () -> {
         return CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.crusty_chunks.crusty_production")).m_257737_(() -> {
            return new ItemStack((ItemLike)CrustyChunksModItems.STEEL_COMPONENT.get());
         }).m_257501_((parameters, tabData) -> {
            tabData.m_246326_(((Block)CrustyChunksModBlocks.THERMAL_FURNACE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BLAST_FURNACE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BLAST_FURNACE_BRICKS.get()).m_5456_());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BLAST_CLAY.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BLAST_FURNACE_BRICK.get());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BLAST_FUNNEL.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.FOUNDRY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.FIREBOX.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ELECTRIC_FIREBOX.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.OIL_FIREBOX.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.REFINERY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.REFINERY_TOWER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.MINERAL_GRINDER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CRUSHER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LATHE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.PRESS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.EXTRUDER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CUTTER.get()).m_5456_());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.CHISEL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HAMMER.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.CUTTERS.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_CASING.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MEDIUM_CASING.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LARGE_CASING.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.EXTRA_LARGE_CASING.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HUGE_CASING.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SHOTGUN_CASING.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_PROJECTILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MEDIUM_PROJECTILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LARGE_PROJECTILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.EXTRA_LARGE_PROJECTILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HUGE_PROJECTILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HOLLOWED_LARGE_PROJECTILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HOLLOWED_EXTRA_LARGE_PROJECTILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HOLLOWED_HUGE_PROJECTILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FOUNDRY_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.COMPONENT_FOUNDRY_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.CYLINDER_FOUNDRY_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_PROJECTILE_FOUNDRY_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MEDIUM_PROJECTILE_FOUNDRY_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LARGE_PROJECTILE_FOUNDRY_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.EXTRA_LARGE_PROJECTILE_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HUGE_PROJECTILE_FOUNDRY_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_UNBORED_BARREL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MEDIUM_UNBORED_BARREL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LARGE_UNBORED_BARREL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HUGE_UNBORED_BARREL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_UNBORED_CANNON_BARREL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MEDIUM_UNBORED_CANNON_BARREL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LARGE_UNBORED_CANNON_BARREL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HUGE_UNBORED_CANNON_BARREL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LARGE_FOUNDRY_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_BARREL_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MEDIUM_BARREL_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LARGE_BARREL_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HUGE_BARREL_FOUNDRY_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_CANNON_FOUNDRY_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MEDIUM_CANNON_FOUNDRY_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LARGE_CANNON_FOUNDRY_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HUGE_CANNON_FOUNDRY_TEMPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_BORED_BARREL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MEDIUM_BORED_BARREL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LARGE_BORED_BARREL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HUGE_BORED_BARREL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.GEIGER_COUNTER.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SOLID_ROCKET_FUEL_PACK.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FIRING_PIN.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.WEAPON_BOLT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FIRING_MECHANISM.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.PISTOL_RECEIVER.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.REVOLVER_RECEIVER.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ADVANCED_PISTOL_RECEIVER.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BASIC_RECEIVER.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BOLT_ACTION_RECEIVER.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.AUTOMATIC_RIFLE_RECEIVER.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ADVANCED_AUTOMATIC_RIFLE_RECEIVER.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMG_RECEIVER.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MG_RECEIVER.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.RIFLE_STOCK.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_HE_PROJECTILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HE_PROJECTILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FLAK_PROJECTILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HEAT_PROJECTILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.APFSDS_PROJECTILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.THERMOMETER.get());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CENTRIFUGE_BOTTOM.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CENTRIFUGE_CORE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CENTRIFUGE_TOP.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.GIANT_COIL.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.REACTION_CHAMBER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BREEDER_REACTOR_PORT.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BLOCK_MINER.get()).m_5456_());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HAND_DRILL.get());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BREEDER_REACTOR_CORE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BREEDER_REACTOR_INTERFACE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.REACTOR_CASING.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CONTROL_ROD.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.EMPTY_FUEL_RODS.get()).m_5456_());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FUEL_ROD.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.WEAPON_SUPRESSOR.get());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.POWER_REACTOR_INTERFACE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.POWER_REACTOR_PORT.get()).m_5456_());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_FLAK_PROJECTILE.get());
         }).withTabsBefore(new ResourceLocation[]{CRUSTY_ORES.getId()}).m_257652_();
      });
      WARIUM_LOGISTICS = REGISTRY.register("warium_logistics", () -> {
         return CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.crusty_chunks.warium_logistics")).m_257737_(() -> {
            return new ItemStack((ItemLike)CrustyChunksModBlocks.CONVEYOR.get());
         }).m_257501_((parameters, tabData) -> {
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CONVEYOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CONVEYOR_DROPOFF.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CONVEYOR_LIFT.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.GENERATOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ENERGY_NODE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ENERGY_BATTERY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LARGE_ELECTRIC_MOTOR.get()).m_5456_());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.CABLE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ENERGY_METER.get());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIGHT_COMBUSTION_ENGINE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.JET_COMPRESSOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.JET_TURBINE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.JET_EXHAUST.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.AFTER_BURNER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.JET_GEARBOX.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.PASSENGER_SEAT.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.FUEL_TANK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.FUEL_TANK_MODULE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.FUEL_TANK_INPUT.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LARGE_ENGINE_SMOKESTACK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ENGINE_CYLLINDER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.DRIVE_SHAFT.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.EXTENSION_SHAFT.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ENERGY_DISTRIBUTION_NODE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.MANUAL_CRANK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.SOLAR_GENERATOR.get()).m_5456_());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FUEL_HOSE.get());
         }).withTabsBefore(new ResourceLocation[]{CRUSTY_PRODUCTION.getId()}).m_257652_();
      });
      CRUSTY_COMPONENTS = REGISTRY.register("crusty_components", () -> {
         return CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.crusty_chunks.crusty_components")).m_257737_(() -> {
            return new ItemStack((ItemLike)CrustyChunksModItems.STEELPLATE.get());
         }).m_257501_((parameters, tabData) -> {
            tabData.m_246326_((ItemLike)CrustyChunksModItems.WOOD_COMPONENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.STEELPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ALUMINUM_PLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BRASS_PLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.COPPER_PLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BENT_COMPONENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.IRONGEAR.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.STEEL_GEAR.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.STEEL_COMPONENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ADVANCED_COMPONENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.CAST_COMPONENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.STEEL_CYLINDER.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.STEEL_SPRING.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.STEEL_TUBE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.STEEL_WIRE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.CUT_COMPONENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BORED_COMPONENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.COPPER_COIL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.COPPER_WIRE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.COMBUSTION_CYLINDER.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ELECTRIC_MOTOR.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ENGINE_COMPONENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_ENGINE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.TECH_COMPONENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.RADAR_COMPONENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.IR_COMPONENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.VOLATILE_DUST.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.PROPELLENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LARGE_VOLATILE_PILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMOKE_AGENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FIRE_AGENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.TOXIC_AGENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.IMPACT_FUZE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.TIMED_FUZE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SHAPED_CHARGE_FUZE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.IMPLOSION_MODULE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.NEUTRON_REFLECTOR.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SHIELDING_COMPONENT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.PLUTONIUM_CORE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.THERMO_NUCLEAR_FUEL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BRASS_FITTING.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.TURBINE_ROTOR.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.POWER_CELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.PAINT_TOOL.get());
         }).withTabsBefore(new ResourceLocation[]{WARIUM_LOGISTICS.getId()}).m_257652_();
      });
      CRUSTY_BUILDING = REGISTRY.register("crusty_building", () -> {
         return CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.crusty_chunks.crusty_building")).m_257737_(() -> {
            return new ItemStack((ItemLike)CrustyChunksModBlocks.SHEET_METAL.get());
         }).m_257501_((parameters, tabData) -> {
            tabData.m_246326_(((Block)CrustyChunksModBlocks.REENFORCED_CONCRETE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RAZOR_WIRE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.WIRE_FENCE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CONCRETE_WALL.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.SHEET_METAL.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.SHEET_METAL_PANE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.REBAR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ASPHALT.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ASPHALT_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.SHEET_METAL_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.SHEET_METAL_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.SAND_BAGS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.STEEL_DOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.OVERGROWN_REENFORCED_CONCRETE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RUSTY_BLOCK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RUSTY_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RUSTY_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RUSTY_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.STRUCTURAL_CONCRETE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.STEEL_TRUSS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.GLASS_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.REINFORCED_GLASS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.REINFORCED_GLASS_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.POLISHED_TRINITITE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.TINTED_GLASS_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.SIREN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ANCIENT_LIGHT.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.TRINITITE_GLASS_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.TRINITITE_GLASS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.POLISHED_BAUXITE.get()).m_5456_());
         }).withTabsBefore(new ResourceLocation[]{CRUSTY_COMPONENTS.getId()}).m_257652_();
      });
      WARIUM_AMMUNITION = REGISTRY.register("warium_ammunition", () -> {
         return CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.crusty_chunks.warium_ammunition")).m_257737_(() -> {
            return new ItemStack((ItemLike)CrustyChunksModItems.ARTILLERY_SHELL.get());
         }).m_257501_((parameters, tabData) -> {
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALLBULLET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_HOLLOW_POINT_BULLET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_STEALTH_BULLET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MEDIUM_AP_BULLET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BULLET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MEDIUM_STEALTH_BULLET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.AP_LARGE_BULLET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LARGE_BULLET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.STEALTH_LARGE_BULLET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SLUG_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SHOTGUN_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BIRD_SHOT.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.EXTRA_LARGE_BULLET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HUGE_BULLET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALL_FLAK_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SOLID_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LARGE_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.HEAT_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.AP_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FLAK_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ARTILLERY_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.GAS_ARTILLERY_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FIRE_ARTILLERY_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ARTILLERY_SOLID_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.POWDER_CHARGE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MORTAR_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMOKE_MORTAR_SHELL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ARMOR_PEELER_ROCKET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FIRE_SPEAR_ROCKET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SEEKER_SPEAR_ROCKET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.RADAR_SPEAR_MISSILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.STRIKE_SPEAR_MISSILE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FLARE_CHARGE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.CHAFF_CHARGE.get());
         }).withTabsBefore(new ResourceLocation[]{CRUSTY_BUILDING.getId()}).m_257652_();
      });
      CRUSTY_ARSENAL = REGISTRY.register("crusty_arsenal", () -> {
         return CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.crusty_chunks.crusty_arsenal")).m_257737_(() -> {
            return new ItemStack((ItemLike)CrustyChunksModBlocks.MACHINE_GUN.get());
         }).m_257501_((parameters, tabData) -> {
            tabData.m_246326_((ItemLike)CrustyChunksModItems.GRENADE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.INCENDIARY_GRENADE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMOKE_GRENADE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.INCENDIARY_BOTTLE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMALLMAGAZINE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMG_MAGAZINE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MEDIUM_MAGAZINE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LARGE_MAGAZINE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LMG_MAGAZINE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MACHINE_GUN_BOX.get());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.AUTOCANNON_DRUM.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.MACHINE_GUN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.MACHINE_GUN_BARREL.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.SMOKE_LAUNCHER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.MORTAR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ROTARY_AUTO_CANNON.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RAC_BARREL.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.AUTOCANNON.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIGHT_AUTOCANNON.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.AUTOCANNON_BARREL.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BATTLE_CANNON_BREECH.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BATTLE_CANNON_BARREL.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ARTILLERYBREECH.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ARTILLERY_BARREL.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.AUTOLOADER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ARTILLERY_CHARGE_LOADER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ARTILLERY_AUTOLOADER.get()).m_5456_());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.AUTO_PISTOL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SEMI_AUTOMATIC_PISTOL_ANIMATED.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.STEALTH_PISTOL.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.REVOLVER_ANIMATED.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SMG_ANIMATED.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.MACHINE_CARBINE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LEVER_RIFLE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SEMI_AUTOMATIC_RIFLE_ANIMATED.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.AUTOMATIC_RIFLE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BURST_RIFLE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.LMG_ANIMATED.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BATTLE_RIFLE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BOLT_ACTION_RIFLE_ANIMATED.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SCOPED_BOLT_ACTION_RIFLE_ANIMATED.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BREAK_ACTION_SHOTGUN_ANIMATED.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.PUMP_ACTION_SHOTGUN_ANIMATED.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BREECH_RIFLE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SCOPED_BREECH_RIFLE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.SINGLE_SHOT_RIFLE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FLAME_THROWER_ANIMATED.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ARMOR_PEELER_UNLOADED.get());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.TORPEDO_THRUSTER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.TORPEDO_CORE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.TORPEDO_WARHEAD.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ROCKET_POD.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ROCKET_POD_CHAMBER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LARGE_ROCKET_POD_CHAMBER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LARGE_ROCKET_POD.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.MANUAL_AIMER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.AIMER_NODE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.NODE_TRIGGER.get()).m_5456_());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.AIMER.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.GAS_MASK_HELMET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BULLET_RESISTANT_HELMET_HELMET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BULLET_RESISTANT_HELMET_2_HELMET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BULLET_RESISTANT_HELMET_3_HELMET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BULLET_RESISTANT_HELMET_4_HELMET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.NVD_HELMET_HELMET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BODY_ARMOR_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FLAME_THROWER_TANK_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FLARE_PISTOL.get());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.COUNTERMEASURE_DISPENSER.get()).m_5456_());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BLAST_ARMOR_HELMET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BLAST_ARMOR_CHESTPLATE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BLAST_ARMOR_LEGGINGS.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.BLAST_ARMOR_BOOTS.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.GAS_MASK_HELMET_HELMET.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.ERADICATION.get());
         }).withTabsBefore(new ResourceLocation[]{WARIUM_AMMUNITION.getId()}).m_257652_();
      });
      CRUSTY_EXPLOSIVES = REGISTRY.register("crusty_explosives", () -> {
         return CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.crusty_chunks.crusty_explosives")).m_257737_(() -> {
            return new ItemStack((ItemLike)CrustyChunksModBlocks.REDSTONE_TNT.get());
         }).m_257501_((parameters, tabData) -> {
            tabData.m_246326_(((Block)CrustyChunksModBlocks.EMPTY_MISSILE_HARDPOINT.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.SMOKE_BOMB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.EXPLOSIVE_BARREL.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.GAS_BOMB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.SMALL_BOMB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CLUSTER_OF_BOMBS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.REDSTONE_TNT.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORDINANCE_CORE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORDINANCE_THRUSTER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORDINANCE_FINS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORDINANCE_HEAVY_WARHEAD.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORDINANCE_INCENDIARY_WARHEAD.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORDINANCE_INLINE_WARHEAD.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORDINANCE_KINETIC_HEAD.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORDINANCE_IR_SEEKER_HEAD.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORDINANCE_SARH_SEEKER.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORDINANCE_CLUSTER_WARHEAD.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORDINANCE_INLINE_FISSION_WARHEAD.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORDINANCE_INLINE_FUSION_WARHEAD_STAGE_1.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORDINANCE_INLINE_FUSION_WARHEAD_STAGE_2.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORDINANCE_FISSION_INITIATOR_HEAD.get()).m_5456_());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FISSION_CORE.get());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.IMPLOSION_LENS.get());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.FISSION_BOMB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.FUSION_BOMB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LAND_MINE.get()).m_5456_());
            tabData.m_246326_((ItemLike)CrustyChunksModItems.FUSION_CORE.get());
         }).withTabsBefore(new ResourceLocation[]{CRUSTY_ARSENAL.getId()}).m_257652_();
      });
      WARIUM_ARMOR = REGISTRY.register("warium_armor", () -> {
         return CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.crusty_chunks.warium_armor")).m_257737_(() -> {
            return new ItemStack((ItemLike)CrustyChunksModBlocks.STEEL_PLATING.get());
         }).m_257501_((parameters, tabData) -> {
            tabData.m_246326_(((Block)CrustyChunksModBlocks.STEEL_PLATING.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.STEEL_PLATING_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.STEEL_PLATING_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.STEEL_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.STEEL_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.GREEN_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.GREEN_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.GREEN_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.GREEN_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.GREEN_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.YELLOW_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.YELLOW_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.YELLOW_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.YELLOW_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.YELLOW_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BROWN_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BROWN_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BROWN_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BROWN_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BROWN_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.WHITE_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.WHITE_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.WHITE_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.WHITE_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.WHITE_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RED_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RED_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RED_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RED_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.RED_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BLACK_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BLACK_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BLACK_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BLACK_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BLACK_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CYAN_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CYAN_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CYAN_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CYAN_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.CYAN_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BLUE_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BLUE_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BLUE_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BLUE_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.BLUE_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORANGE_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORANGE_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORANGE_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORANGE_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ORANGE_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.GRAY_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.GRAY_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.GRAY_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.GRAY_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.GRAY_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIME_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIME_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIME_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIME_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIME_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIGHT_GRAY_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIGHT_GRAY_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIGHT_GRAY_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIGHT_GRAY_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIGHT_GRAY_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIGHT_BLUE_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIGHT_BLUE_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIGHT_BLUE_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIGHT_BLUE_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.LIGHT_BLUE_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.PINK_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.PINK_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.PINK_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.PINK_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.PINK_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.MAGENTA_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.MAGENTA_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.MAGENTA_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.MAGENTA_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.MAGENTA_ARMOR_OPTIC.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.PURPLE_ARMOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.PURPLE_ARMOR_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.PURPLE_ARMOR_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.PURPLE_ARMOR_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.PURPLE_ARMOR_OPTIC.get()).m_5456_());
         }).withTabsBefore(new ResourceLocation[]{CRUSTY_EXPLOSIVES.getId()}).m_257652_();
      });
      WARIUM_ALUMINUM = REGISTRY.register("warium_aluminum", () -> {
         return CreativeModeTab.builder().m_257941_(Component.m_237115_("item_group.crusty_chunks.warium_aluminum")).m_257737_(() -> {
            return new ItemStack((ItemLike)CrustyChunksModBlocks.ALUMINUM_PLATING.get());
         }).m_257501_((parameters, tabData) -> {
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_DARK_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_DARK_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_DARK_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_DARK_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_DARK_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_DARK_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_GREEN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_GREEN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_GREEN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_GREEN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_GREEN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_GREEN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_YELLOW.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_YELLOW.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_YELLOW.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_YELLOW.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_YELLOW.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_YELLOW.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_BROWN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_BROWN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_BROWN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_BROWN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_BROWN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_BROWN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_RED.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_RED.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_RED.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_RED.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_RED.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_RED.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_WHITE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_WHITE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_WHITE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_WHITE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_WHITE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_WHITE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_BLUE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_BLUE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_BLUE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_BLUE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_BLUE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_BLUE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_ORANGE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_ORANGE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_ORANGE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_ORANGE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_ORANGE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_ORANGE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_CYAN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_CYAN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_CYAN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_CYAN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_CYAN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_CYAN.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_BLACK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_BLACK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_BLACK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_BLACK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_BLACK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_BLACK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_LIGHT_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_LIGHT_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_LIGHT_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_LIGHT_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_LIGHT_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_LIGHT_GRAY.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_LIME.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_LIME.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_LIME.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_LIME.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_LIME.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_LIME.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_LIGHT_BLUE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_LIGHT_BLUE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_LIGHT_BLUE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_LIGHT_BLUE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_LIGHT_BLUE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_LIGHT_BLUE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_PINK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_PINK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_PINK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_PINK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_PINK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_PINK.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_MAGENTA.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_MAGENTA.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_MAGENTA.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_MAGENTA.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_MAGENTA.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_MAGENTA.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_PURPLE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_SLAB_PURPLE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_STAIRS_PURPLE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_PLATING_TRAPDOOR_PURPLE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_SIDE_PANEL_PURPLE.get()).m_5456_());
            tabData.m_246326_(((Block)CrustyChunksModBlocks.ALUMINUM_AC_BARREL_PURPLE.get()).m_5456_());
         }).withTabsBefore(new ResourceLocation[]{WARIUM_ARMOR.getId()}).m_257652_();
      });
   }
}
