package net.mcreator.crustychunks.init;

import com.mojang.datafixers.types.Type;
import net.mcreator.crustychunks.block.entity.ActiveRobotChuteBlockEntity;
import net.mcreator.crustychunks.block.entity.AfterBurnerBlockEntity;
import net.mcreator.crustychunks.block.entity.AimerNodeBlockEntity;
import net.mcreator.crustychunks.block.entity.ArtilleryAutoloaderBlockEntity;
import net.mcreator.crustychunks.block.entity.ArtilleryBarrelBlockEntity;
import net.mcreator.crustychunks.block.entity.ArtilleryChargeLoaderBlockEntity;
import net.mcreator.crustychunks.block.entity.ArtillerybreechBlockEntity;
import net.mcreator.crustychunks.block.entity.AutocannonBarrelBlockEntity;
import net.mcreator.crustychunks.block.entity.AutocannonBlockEntity;
import net.mcreator.crustychunks.block.entity.AutocannonDrumBlockEntity;
import net.mcreator.crustychunks.block.entity.AutoloaderBlockEntity;
import net.mcreator.crustychunks.block.entity.BattleCannonBarrelBlockEntity;
import net.mcreator.crustychunks.block.entity.BattleCannonBreechBlockEntity;
import net.mcreator.crustychunks.block.entity.BlastFurnaceBlockEntity;
import net.mcreator.crustychunks.block.entity.BlockMinerBlockEntity;
import net.mcreator.crustychunks.block.entity.BreederReactorCoreBlockEntity;
import net.mcreator.crustychunks.block.entity.BreederReactorInterfaceBlockEntity;
import net.mcreator.crustychunks.block.entity.BreederReactorPortBlockEntity;
import net.mcreator.crustychunks.block.entity.CentrifugeBottomBlockEntity;
import net.mcreator.crustychunks.block.entity.CentrifugeCoreBlockEntity;
import net.mcreator.crustychunks.block.entity.CentrifugeTopBlockEntity;
import net.mcreator.crustychunks.block.entity.ClusterOfBombsBlockEntity;
import net.mcreator.crustychunks.block.entity.ConveyorBlockEntity;
import net.mcreator.crustychunks.block.entity.ConveyorDropoffBlockEntity;
import net.mcreator.crustychunks.block.entity.ConveyorLiftBlockEntity;
import net.mcreator.crustychunks.block.entity.CountermeasureDispenserBlockEntity;
import net.mcreator.crustychunks.block.entity.CrusherBlockEntity;
import net.mcreator.crustychunks.block.entity.CutterBlockEntity;
import net.mcreator.crustychunks.block.entity.DamagedfueltankBlockEntity;
import net.mcreator.crustychunks.block.entity.DefenseCoreBlockEntity;
import net.mcreator.crustychunks.block.entity.DriveShaftBlockEntity;
import net.mcreator.crustychunks.block.entity.ElectricFireboxBlockEntity;
import net.mcreator.crustychunks.block.entity.EmptyMissileHardpointBlockEntity;
import net.mcreator.crustychunks.block.entity.EnergyBatteryBlockEntity;
import net.mcreator.crustychunks.block.entity.EnergyDistributionNodeBlockEntity;
import net.mcreator.crustychunks.block.entity.EnergyNodeBlockEntity;
import net.mcreator.crustychunks.block.entity.EngineCyllinderBlockEntity;
import net.mcreator.crustychunks.block.entity.ExtensionShaftBlockEntity;
import net.mcreator.crustychunks.block.entity.ExtruderBlockEntity;
import net.mcreator.crustychunks.block.entity.FireSpearMissileHardpointBlockEntity;
import net.mcreator.crustychunks.block.entity.FireboxBlockEntity;
import net.mcreator.crustychunks.block.entity.FissionBombBlockEntity;
import net.mcreator.crustychunks.block.entity.FoundryBlockEntity;
import net.mcreator.crustychunks.block.entity.FuelTankBlockEntity;
import net.mcreator.crustychunks.block.entity.FuelTankInputBlockEntity;
import net.mcreator.crustychunks.block.entity.FuelTankModuleBlockEntity;
import net.mcreator.crustychunks.block.entity.FusionBombBlockEntity;
import net.mcreator.crustychunks.block.entity.GasBombBlockEntity;
import net.mcreator.crustychunks.block.entity.GasDispenserBlockEntity;
import net.mcreator.crustychunks.block.entity.GeneratorBlockEntity;
import net.mcreator.crustychunks.block.entity.JetCompressorBlockEntity;
import net.mcreator.crustychunks.block.entity.JetExhaustBlockEntity;
import net.mcreator.crustychunks.block.entity.JetGearboxBlockEntity;
import net.mcreator.crustychunks.block.entity.JetTurbineBlockEntity;
import net.mcreator.crustychunks.block.entity.LargeElectricMotorBlockEntity;
import net.mcreator.crustychunks.block.entity.LargeRocketPodBlockEntity;
import net.mcreator.crustychunks.block.entity.LatheBlockEntity;
import net.mcreator.crustychunks.block.entity.LightAutocannonBlockEntity;
import net.mcreator.crustychunks.block.entity.LightCombustionEngineBlockEntity;
import net.mcreator.crustychunks.block.entity.MachineGunBarrelBlockEntity;
import net.mcreator.crustychunks.block.entity.MachineGunBlockEntity;
import net.mcreator.crustychunks.block.entity.ManualAimerBlockEntity;
import net.mcreator.crustychunks.block.entity.ManualCrankBlockEntity;
import net.mcreator.crustychunks.block.entity.MineralGrinderBlockEntity;
import net.mcreator.crustychunks.block.entity.MortarBlockEntity;
import net.mcreator.crustychunks.block.entity.NodeTriggerBlockEntity;
import net.mcreator.crustychunks.block.entity.NodeTriggerOnBlockEntity;
import net.mcreator.crustychunks.block.entity.OilFireboxBlockEntity;
import net.mcreator.crustychunks.block.entity.OpenSummonationBlockEntity;
import net.mcreator.crustychunks.block.entity.OrdinanceControllerBlockEntity;
import net.mcreator.crustychunks.block.entity.OrdinanceCoreBlockEntity;
import net.mcreator.crustychunks.block.entity.OrdinanceInlineFissionWarheadBlockEntity;
import net.mcreator.crustychunks.block.entity.OrdinanceInlineFusionWarheadStage1BlockEntity;
import net.mcreator.crustychunks.block.entity.PowerReactorInterfaceBlockEntity;
import net.mcreator.crustychunks.block.entity.PowerReactorPortBlockEntity;
import net.mcreator.crustychunks.block.entity.PressBlockEntity;
import net.mcreator.crustychunks.block.entity.RACBarrelTileEntity;
import net.mcreator.crustychunks.block.entity.RadarSpearMissileHardpointBlockEntity;
import net.mcreator.crustychunks.block.entity.ReactionChamberBlockEntity;
import net.mcreator.crustychunks.block.entity.RedstoneTNTBlockEntity;
import net.mcreator.crustychunks.block.entity.RefineryBlockEntity;
import net.mcreator.crustychunks.block.entity.RefineryTowerBlockEntity;
import net.mcreator.crustychunks.block.entity.RobotChuteBlockEntity;
import net.mcreator.crustychunks.block.entity.RocketPodBlockEntity;
import net.mcreator.crustychunks.block.entity.RotaryAutoCannonBlockEntity;
import net.mcreator.crustychunks.block.entity.SeekerSpearMissileHardpointBlockEntity;
import net.mcreator.crustychunks.block.entity.SirenBlockEntity;
import net.mcreator.crustychunks.block.entity.SmallBombBlockEntity;
import net.mcreator.crustychunks.block.entity.SmokeLauncherBlockEntity;
import net.mcreator.crustychunks.block.entity.SolarGeneratorBlockEntity;
import net.mcreator.crustychunks.block.entity.StrikeSpearMissileHardpointBlockEntity;
import net.mcreator.crustychunks.block.entity.SummonationBlockEntity;
import net.mcreator.crustychunks.block.entity.SummonatorActiveBlockEntity;
import net.mcreator.crustychunks.block.entity.SummonatorBlockEntity;
import net.mcreator.crustychunks.block.entity.ThermalFurnaceBlockEntity;
import net.mcreator.crustychunks.block.entity.TorpedoCoreBlockEntity;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.entity.BlockEntityType.BlockEntitySupplier;
import net.minecraft.world.level.block.entity.BlockEntityType.Builder;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class CrustyChunksModBlockEntities {
   public static final DeferredRegister<BlockEntityType<?>> REGISTRY;
   public static final RegistryObject<BlockEntityType<?>> REDSTONE_TNT;
   public static final RegistryObject<BlockEntityType<?>> MACHINE_GUN;
   public static final RegistryObject<BlockEntityType<?>> MACHINE_GUN_BARREL;
   public static final RegistryObject<BlockEntityType<?>> ARTILLERYBREECH;
   public static final RegistryObject<BlockEntityType<?>> ARTILLERY_BARREL;
   public static final RegistryObject<BlockEntityType<?>> BATTLE_CANNON_BREECH;
   public static final RegistryObject<BlockEntityType<?>> BATTLE_CANNON_BARREL;
   public static final RegistryObject<BlockEntityType<?>> BLAST_FURNACE;
   public static final RegistryObject<BlockEntityType<?>> FOUNDRY;
   public static final RegistryObject<BlockEntityType<?>> CONVEYOR;
   public static final RegistryObject<BlockEntityType<?>> CONVEYOR_DROPOFF;
   public static final RegistryObject<BlockEntityType<?>> CONVEYOR_LIFT;
   public static final RegistryObject<BlockEntityType<?>> FIREBOX;
   public static final RegistryObject<BlockEntityType<?>> PRESS;
   public static final RegistryObject<BlockEntityType<?>> EXTRUDER;
   public static final RegistryObject<BlockEntityType<?>> CUTTER;
   public static final RegistryObject<BlockEntityType<?>> AUTOCANNON;
   public static final RegistryObject<BlockEntityType<?>> AUTOCANNON_BARREL;
   public static final RegistryObject<BlockEntityType<?>> AUTOCANNON_DRUM;
   public static final RegistryObject<BlockEntityType<?>> AUTOLOADER;
   public static final RegistryObject<BlockEntityType<?>> LIGHT_COMBUSTION_ENGINE;
   public static final RegistryObject<BlockEntityType<?>> FISSION_BOMB;
   public static final RegistryObject<BlockEntityType<?>> MINERAL_GRINDER;
   public static final RegistryObject<BlockEntityType<?>> SMALL_BOMB;
   public static final RegistryObject<BlockEntityType<?>> CLUSTER_OF_BOMBS;
   public static final RegistryObject<BlockEntityType<?>> ARTILLERY_AUTOLOADER;
   public static final RegistryObject<BlockEntityType<?>> ARTILLERY_CHARGE_LOADER;
   public static final RegistryObject<BlockEntityType<?>> TORPEDO_CORE;
   public static final RegistryObject<BlockEntityType<?>> ROCKET_POD;
   public static final RegistryObject<BlockEntityType<?>> JET_EXHAUST;
   public static final RegistryObject<BlockEntityType<?>> JET_TURBINE;
   public static final RegistryObject<BlockEntityType<?>> JET_COMPRESSOR;
   public static final RegistryObject<BlockEntityType<?>> MORTAR;
   public static final RegistryObject<BlockEntityType<?>> AIMER_NODE;
   public static final RegistryObject<BlockEntityType<?>> SIREN;
   public static final RegistryObject<BlockEntityType<?>> ROTARY_AUTO_CANNON;
   public static final RegistryObject<BlockEntityType<RACBarrelTileEntity>> RAC_BARREL;
   public static final RegistryObject<BlockEntityType<?>> LIGHT_AUTOCANNON;
   public static final RegistryObject<BlockEntityType<?>> SMOKE_LAUNCHER;
   public static final RegistryObject<BlockEntityType<?>> REFINERY;
   public static final RegistryObject<BlockEntityType<?>> REFINERY_TOWER;
   public static final RegistryObject<BlockEntityType<?>> CENTRIFUGE_TOP;
   public static final RegistryObject<BlockEntityType<?>> CENTRIFUGE_CORE;
   public static final RegistryObject<BlockEntityType<?>> CENTRIFUGE_BOTTOM;
   public static final RegistryObject<BlockEntityType<?>> REACTION_CHAMBER;
   public static final RegistryObject<BlockEntityType<?>> BREEDER_REACTOR_PORT;
   public static final RegistryObject<BlockEntityType<?>> BLOCK_MINER;
   public static final RegistryObject<BlockEntityType<?>> OIL_FIREBOX;
   public static final RegistryObject<BlockEntityType<?>> SUMMONATOR;
   public static final RegistryObject<BlockEntityType<?>> ROBOT_CHUTE;
   public static final RegistryObject<BlockEntityType<?>> SUMMONATOR_ACTIVE;
   public static final RegistryObject<BlockEntityType<?>> ACTIVE_ROBOT_CHUTE;
   public static final RegistryObject<BlockEntityType<?>> BREEDER_REACTOR_CORE;
   public static final RegistryObject<BlockEntityType<?>> BREEDER_REACTOR_INTERFACE;
   public static final RegistryObject<BlockEntityType<?>> AFTER_BURNER;
   public static final RegistryObject<BlockEntityType<?>> GAS_BOMB;
   public static final RegistryObject<BlockEntityType<?>> GAS_DISPENSER;
   public static final RegistryObject<BlockEntityType<?>> NODE_TRIGGER;
   public static final RegistryObject<BlockEntityType<?>> NODE_TRIGGER_ON;
   public static final RegistryObject<BlockEntityType<?>> COUNTERMEASURE_DISPENSER;
   public static final RegistryObject<BlockEntityType<?>> ORDINANCE_CORE;
   public static final RegistryObject<BlockEntityType<?>> ORDINANCE_INLINE_FISSION_WARHEAD;
   public static final RegistryObject<BlockEntityType<?>> SUMMONATION;
   public static final RegistryObject<BlockEntityType<?>> OPEN_SUMMONATION;
   public static final RegistryObject<BlockEntityType<?>> DEFENSE_CORE;
   public static final RegistryObject<BlockEntityType<?>> FUSION_BOMB;
   public static final RegistryObject<BlockEntityType<?>> JET_GEARBOX;
   public static final RegistryObject<BlockEntityType<?>> GENERATOR;
   public static final RegistryObject<BlockEntityType<?>> FUEL_TANK;
   public static final RegistryObject<BlockEntityType<?>> EXTENSION_SHAFT;
   public static final RegistryObject<BlockEntityType<?>> DRIVE_SHAFT;
   public static final RegistryObject<BlockEntityType<?>> ENGINE_CYLLINDER;
   public static final RegistryObject<BlockEntityType<?>> ENERGY_NODE;
   public static final RegistryObject<BlockEntityType<?>> ENERGY_BATTERY;
   public static final RegistryObject<BlockEntityType<?>> LARGE_ELECTRIC_MOTOR;
   public static final RegistryObject<BlockEntityType<?>> LATHE;
   public static final RegistryObject<BlockEntityType<?>> ELECTRIC_FIREBOX;
   public static final RegistryObject<BlockEntityType<?>> THERMAL_FURNACE;
   public static final RegistryObject<BlockEntityType<?>> POWER_REACTOR_INTERFACE;
   public static final RegistryObject<BlockEntityType<?>> POWER_REACTOR_PORT;
   public static final RegistryObject<BlockEntityType<?>> ORDINANCE_INLINE_FUSION_WARHEAD_STAGE_1;
   public static final RegistryObject<BlockEntityType<?>> CRUSHER;
   public static final RegistryObject<BlockEntityType<?>> ENERGY_DISTRIBUTION_NODE;
   public static final RegistryObject<BlockEntityType<?>> MANUAL_CRANK;
   public static final RegistryObject<BlockEntityType<?>> LARGE_ROCKET_POD;
   public static final RegistryObject<BlockEntityType<?>> EMPTY_MISSILE_HARDPOINT;
   public static final RegistryObject<BlockEntityType<?>> FIRE_SPEAR_MISSILE_HARDPOINT;
   public static final RegistryObject<BlockEntityType<?>> SEEKER_SPEAR_MISSILE_HARDPOINT;
   public static final RegistryObject<BlockEntityType<?>> STRIKE_SPEAR_MISSILE_HARDPOINT;
   public static final RegistryObject<BlockEntityType<?>> MANUAL_AIMER;
   public static final RegistryObject<BlockEntityType<?>> SOLAR_GENERATOR;
   public static final RegistryObject<BlockEntityType<?>> RADAR_SPEAR_MISSILE_HARDPOINT;
   public static final RegistryObject<BlockEntityType<?>> ORDINANCE_CONTROLLER;
   public static final RegistryObject<BlockEntityType<?>> FUEL_TANK_MODULE;
   public static final RegistryObject<BlockEntityType<?>> DAMAGEDFUELTANK;
   public static final RegistryObject<BlockEntityType<?>> FUEL_TANK_INPUT;

   private static RegistryObject<BlockEntityType<?>> register(String registryname, RegistryObject<Block> block, BlockEntitySupplier<?> supplier) {
      return REGISTRY.register(registryname, () -> {
         return Builder.m_155273_(supplier, new Block[]{(Block)block.get()}).m_58966_((Type)null);
      });
   }

   static {
      REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCK_ENTITY_TYPES, "crusty_chunks");
      REDSTONE_TNT = register("redstone_tnt", CrustyChunksModBlocks.REDSTONE_TNT, RedstoneTNTBlockEntity::new);
      MACHINE_GUN = register("machine_gun", CrustyChunksModBlocks.MACHINE_GUN, MachineGunBlockEntity::new);
      MACHINE_GUN_BARREL = register("machine_gun_barrel", CrustyChunksModBlocks.MACHINE_GUN_BARREL, MachineGunBarrelBlockEntity::new);
      ARTILLERYBREECH = register("artillerybreech", CrustyChunksModBlocks.ARTILLERYBREECH, ArtillerybreechBlockEntity::new);
      ARTILLERY_BARREL = register("artillery_barrel", CrustyChunksModBlocks.ARTILLERY_BARREL, ArtilleryBarrelBlockEntity::new);
      BATTLE_CANNON_BREECH = register("battle_cannon_breech", CrustyChunksModBlocks.BATTLE_CANNON_BREECH, BattleCannonBreechBlockEntity::new);
      BATTLE_CANNON_BARREL = register("battle_cannon_barrel", CrustyChunksModBlocks.BATTLE_CANNON_BARREL, BattleCannonBarrelBlockEntity::new);
      BLAST_FURNACE = register("blast_furnace", CrustyChunksModBlocks.BLAST_FURNACE, BlastFurnaceBlockEntity::new);
      FOUNDRY = register("foundry", CrustyChunksModBlocks.FOUNDRY, FoundryBlockEntity::new);
      CONVEYOR = register("conveyor", CrustyChunksModBlocks.CONVEYOR, ConveyorBlockEntity::new);
      CONVEYOR_DROPOFF = register("conveyor_dropoff", CrustyChunksModBlocks.CONVEYOR_DROPOFF, ConveyorDropoffBlockEntity::new);
      CONVEYOR_LIFT = register("conveyor_lift", CrustyChunksModBlocks.CONVEYOR_LIFT, ConveyorLiftBlockEntity::new);
      FIREBOX = register("firebox", CrustyChunksModBlocks.FIREBOX, FireboxBlockEntity::new);
      PRESS = register("press", CrustyChunksModBlocks.PRESS, PressBlockEntity::new);
      EXTRUDER = register("extruder", CrustyChunksModBlocks.EXTRUDER, ExtruderBlockEntity::new);
      CUTTER = register("cutter", CrustyChunksModBlocks.CUTTER, CutterBlockEntity::new);
      AUTOCANNON = register("autocannon", CrustyChunksModBlocks.AUTOCANNON, AutocannonBlockEntity::new);
      AUTOCANNON_BARREL = register("autocannon_barrel", CrustyChunksModBlocks.AUTOCANNON_BARREL, AutocannonBarrelBlockEntity::new);
      AUTOCANNON_DRUM = register("autocannon_drum", CrustyChunksModBlocks.AUTOCANNON_DRUM, AutocannonDrumBlockEntity::new);
      AUTOLOADER = register("autoloader", CrustyChunksModBlocks.AUTOLOADER, AutoloaderBlockEntity::new);
      LIGHT_COMBUSTION_ENGINE = register("light_combustion_engine", CrustyChunksModBlocks.LIGHT_COMBUSTION_ENGINE, LightCombustionEngineBlockEntity::new);
      FISSION_BOMB = register("fission_bomb", CrustyChunksModBlocks.FISSION_BOMB, FissionBombBlockEntity::new);
      MINERAL_GRINDER = register("mineral_grinder", CrustyChunksModBlocks.MINERAL_GRINDER, MineralGrinderBlockEntity::new);
      SMALL_BOMB = register("small_bomb", CrustyChunksModBlocks.SMALL_BOMB, SmallBombBlockEntity::new);
      CLUSTER_OF_BOMBS = register("cluster_of_bombs", CrustyChunksModBlocks.CLUSTER_OF_BOMBS, ClusterOfBombsBlockEntity::new);
      ARTILLERY_AUTOLOADER = register("artillery_autoloader", CrustyChunksModBlocks.ARTILLERY_AUTOLOADER, ArtilleryAutoloaderBlockEntity::new);
      ARTILLERY_CHARGE_LOADER = register("artillery_charge_loader", CrustyChunksModBlocks.ARTILLERY_CHARGE_LOADER, ArtilleryChargeLoaderBlockEntity::new);
      TORPEDO_CORE = register("torpedo_core", CrustyChunksModBlocks.TORPEDO_CORE, TorpedoCoreBlockEntity::new);
      ROCKET_POD = register("rocket_pod", CrustyChunksModBlocks.ROCKET_POD, RocketPodBlockEntity::new);
      JET_EXHAUST = register("jet_exhaust", CrustyChunksModBlocks.JET_EXHAUST, JetExhaustBlockEntity::new);
      JET_TURBINE = register("jet_turbine", CrustyChunksModBlocks.JET_TURBINE, JetTurbineBlockEntity::new);
      JET_COMPRESSOR = register("jet_compressor", CrustyChunksModBlocks.JET_COMPRESSOR, JetCompressorBlockEntity::new);
      MORTAR = register("mortar", CrustyChunksModBlocks.MORTAR, MortarBlockEntity::new);
      AIMER_NODE = register("aimer_node", CrustyChunksModBlocks.AIMER_NODE, AimerNodeBlockEntity::new);
      SIREN = register("siren", CrustyChunksModBlocks.SIREN, SirenBlockEntity::new);
      ROTARY_AUTO_CANNON = register("rotary_auto_cannon", CrustyChunksModBlocks.ROTARY_AUTO_CANNON, RotaryAutoCannonBlockEntity::new);
      RAC_BARREL = REGISTRY.register("rac_barrel", () -> {
         return Builder.m_155273_(RACBarrelTileEntity::new, new Block[]{(Block)CrustyChunksModBlocks.RAC_BARREL.get()}).m_58966_((Type)null);
      });
      LIGHT_AUTOCANNON = register("light_autocannon", CrustyChunksModBlocks.LIGHT_AUTOCANNON, LightAutocannonBlockEntity::new);
      SMOKE_LAUNCHER = register("smoke_launcher", CrustyChunksModBlocks.SMOKE_LAUNCHER, SmokeLauncherBlockEntity::new);
      REFINERY = register("refinery", CrustyChunksModBlocks.REFINERY, RefineryBlockEntity::new);
      REFINERY_TOWER = register("refinery_tower", CrustyChunksModBlocks.REFINERY_TOWER, RefineryTowerBlockEntity::new);
      CENTRIFUGE_TOP = register("centrifuge_top", CrustyChunksModBlocks.CENTRIFUGE_TOP, CentrifugeTopBlockEntity::new);
      CENTRIFUGE_CORE = register("centrifuge_core", CrustyChunksModBlocks.CENTRIFUGE_CORE, CentrifugeCoreBlockEntity::new);
      CENTRIFUGE_BOTTOM = register("centrifuge_bottom", CrustyChunksModBlocks.CENTRIFUGE_BOTTOM, CentrifugeBottomBlockEntity::new);
      REACTION_CHAMBER = register("reaction_chamber", CrustyChunksModBlocks.REACTION_CHAMBER, ReactionChamberBlockEntity::new);
      BREEDER_REACTOR_PORT = register("breeder_reactor_port", CrustyChunksModBlocks.BREEDER_REACTOR_PORT, BreederReactorPortBlockEntity::new);
      BLOCK_MINER = register("block_miner", CrustyChunksModBlocks.BLOCK_MINER, BlockMinerBlockEntity::new);
      OIL_FIREBOX = register("oil_firebox", CrustyChunksModBlocks.OIL_FIREBOX, OilFireboxBlockEntity::new);
      SUMMONATOR = register("summonator", CrustyChunksModBlocks.SUMMONATOR, SummonatorBlockEntity::new);
      ROBOT_CHUTE = register("robot_chute", CrustyChunksModBlocks.ROBOT_CHUTE, RobotChuteBlockEntity::new);
      SUMMONATOR_ACTIVE = register("summonator_active", CrustyChunksModBlocks.SUMMONATOR_ACTIVE, SummonatorActiveBlockEntity::new);
      ACTIVE_ROBOT_CHUTE = register("active_robot_chute", CrustyChunksModBlocks.ACTIVE_ROBOT_CHUTE, ActiveRobotChuteBlockEntity::new);
      BREEDER_REACTOR_CORE = register("breeder_reactor_core", CrustyChunksModBlocks.BREEDER_REACTOR_CORE, BreederReactorCoreBlockEntity::new);
      BREEDER_REACTOR_INTERFACE = register("breeder_reactor_interface", CrustyChunksModBlocks.BREEDER_REACTOR_INTERFACE, BreederReactorInterfaceBlockEntity::new);
      AFTER_BURNER = register("after_burner", CrustyChunksModBlocks.AFTER_BURNER, AfterBurnerBlockEntity::new);
      GAS_BOMB = register("gas_bomb", CrustyChunksModBlocks.GAS_BOMB, GasBombBlockEntity::new);
      GAS_DISPENSER = register("gas_dispenser", CrustyChunksModBlocks.GAS_DISPENSER, GasDispenserBlockEntity::new);
      NODE_TRIGGER = register("node_trigger", CrustyChunksModBlocks.NODE_TRIGGER, NodeTriggerBlockEntity::new);
      NODE_TRIGGER_ON = register("node_trigger_on", CrustyChunksModBlocks.NODE_TRIGGER_ON, NodeTriggerOnBlockEntity::new);
      COUNTERMEASURE_DISPENSER = register("countermeasure_dispenser", CrustyChunksModBlocks.COUNTERMEASURE_DISPENSER, CountermeasureDispenserBlockEntity::new);
      ORDINANCE_CORE = register("ordinance_core", CrustyChunksModBlocks.ORDINANCE_CORE, OrdinanceCoreBlockEntity::new);
      ORDINANCE_INLINE_FISSION_WARHEAD = register("ordinance_inline_fission_warhead", CrustyChunksModBlocks.ORDINANCE_INLINE_FISSION_WARHEAD, OrdinanceInlineFissionWarheadBlockEntity::new);
      SUMMONATION = register("summonation", CrustyChunksModBlocks.SUMMONATION, SummonationBlockEntity::new);
      OPEN_SUMMONATION = register("open_summonation", CrustyChunksModBlocks.OPEN_SUMMONATION, OpenSummonationBlockEntity::new);
      DEFENSE_CORE = register("defense_core", CrustyChunksModBlocks.DEFENSE_CORE, DefenseCoreBlockEntity::new);
      FUSION_BOMB = register("fusion_bomb", CrustyChunksModBlocks.FUSION_BOMB, FusionBombBlockEntity::new);
      JET_GEARBOX = register("jet_gearbox", CrustyChunksModBlocks.JET_GEARBOX, JetGearboxBlockEntity::new);
      GENERATOR = register("generator", CrustyChunksModBlocks.GENERATOR, GeneratorBlockEntity::new);
      FUEL_TANK = register("fuel_tank", CrustyChunksModBlocks.FUEL_TANK, FuelTankBlockEntity::new);
      EXTENSION_SHAFT = register("extension_shaft", CrustyChunksModBlocks.EXTENSION_SHAFT, ExtensionShaftBlockEntity::new);
      DRIVE_SHAFT = register("drive_shaft", CrustyChunksModBlocks.DRIVE_SHAFT, DriveShaftBlockEntity::new);
      ENGINE_CYLLINDER = register("engine_cyllinder", CrustyChunksModBlocks.ENGINE_CYLLINDER, EngineCyllinderBlockEntity::new);
      ENERGY_NODE = register("energy_node", CrustyChunksModBlocks.ENERGY_NODE, EnergyNodeBlockEntity::new);
      ENERGY_BATTERY = register("energy_battery", CrustyChunksModBlocks.ENERGY_BATTERY, EnergyBatteryBlockEntity::new);
      LARGE_ELECTRIC_MOTOR = register("large_electric_motor", CrustyChunksModBlocks.LARGE_ELECTRIC_MOTOR, LargeElectricMotorBlockEntity::new);
      LATHE = register("lathe", CrustyChunksModBlocks.LATHE, LatheBlockEntity::new);
      ELECTRIC_FIREBOX = register("electric_firebox", CrustyChunksModBlocks.ELECTRIC_FIREBOX, ElectricFireboxBlockEntity::new);
      THERMAL_FURNACE = register("thermal_furnace", CrustyChunksModBlocks.THERMAL_FURNACE, ThermalFurnaceBlockEntity::new);
      POWER_REACTOR_INTERFACE = register("power_reactor_interface", CrustyChunksModBlocks.POWER_REACTOR_INTERFACE, PowerReactorInterfaceBlockEntity::new);
      POWER_REACTOR_PORT = register("power_reactor_port", CrustyChunksModBlocks.POWER_REACTOR_PORT, PowerReactorPortBlockEntity::new);
      ORDINANCE_INLINE_FUSION_WARHEAD_STAGE_1 = register("ordinance_inline_fusion_warhead_stage_1", CrustyChunksModBlocks.ORDINANCE_INLINE_FUSION_WARHEAD_STAGE_1, OrdinanceInlineFusionWarheadStage1BlockEntity::new);
      CRUSHER = register("crusher", CrustyChunksModBlocks.CRUSHER, CrusherBlockEntity::new);
      ENERGY_DISTRIBUTION_NODE = register("energy_distribution_node", CrustyChunksModBlocks.ENERGY_DISTRIBUTION_NODE, EnergyDistributionNodeBlockEntity::new);
      MANUAL_CRANK = register("manual_crank", CrustyChunksModBlocks.MANUAL_CRANK, ManualCrankBlockEntity::new);
      LARGE_ROCKET_POD = register("large_rocket_pod", CrustyChunksModBlocks.LARGE_ROCKET_POD, LargeRocketPodBlockEntity::new);
      EMPTY_MISSILE_HARDPOINT = register("empty_missile_hardpoint", CrustyChunksModBlocks.EMPTY_MISSILE_HARDPOINT, EmptyMissileHardpointBlockEntity::new);
      FIRE_SPEAR_MISSILE_HARDPOINT = register("fire_spear_missile_hardpoint", CrustyChunksModBlocks.FIRE_SPEAR_MISSILE_HARDPOINT, FireSpearMissileHardpointBlockEntity::new);
      SEEKER_SPEAR_MISSILE_HARDPOINT = register("seeker_spear_missile_hardpoint", CrustyChunksModBlocks.SEEKER_SPEAR_MISSILE_HARDPOINT, SeekerSpearMissileHardpointBlockEntity::new);
      STRIKE_SPEAR_MISSILE_HARDPOINT = register("strike_spear_missile_hardpoint", CrustyChunksModBlocks.STRIKE_SPEAR_MISSILE_HARDPOINT, StrikeSpearMissileHardpointBlockEntity::new);
      MANUAL_AIMER = register("manual_aimer", CrustyChunksModBlocks.MANUAL_AIMER, ManualAimerBlockEntity::new);
      SOLAR_GENERATOR = register("solar_generator", CrustyChunksModBlocks.SOLAR_GENERATOR, SolarGeneratorBlockEntity::new);
      RADAR_SPEAR_MISSILE_HARDPOINT = register("radar_spear_missile_hardpoint", CrustyChunksModBlocks.RADAR_SPEAR_MISSILE_HARDPOINT, RadarSpearMissileHardpointBlockEntity::new);
      ORDINANCE_CONTROLLER = register("ordinance_controller", CrustyChunksModBlocks.ORDINANCE_CONTROLLER, OrdinanceControllerBlockEntity::new);
      FUEL_TANK_MODULE = register("fuel_tank_module", CrustyChunksModBlocks.FUEL_TANK_MODULE, FuelTankModuleBlockEntity::new);
      DAMAGEDFUELTANK = register("damagedfueltank", CrustyChunksModBlocks.DAMAGEDFUELTANK, DamagedfueltankBlockEntity::new);
      FUEL_TANK_INPUT = register("fuel_tank_input", CrustyChunksModBlocks.FUEL_TANK_INPUT, FuelTankInputBlockEntity::new);
   }
}
