modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="crusty_chunks"
version="1.0.7"
displayName="Warium"
displayURL="https://mcreator.net"
credits="(I did use Mcreator for much of this, but it is probably one of the best Mcreator mods ever made)- https://mcreator.net/about"
authors="NovaManGood2110"
description="A semi-modern warfare technology mod that adds cannons bombs and weapons. (Alpha)"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.crusty_chunks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.crusty_chunks]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration